### ISSUE TITLE
Swift support?

### ISSUE THREAD

**Issue by zubingala** [syaringan357/iOS-MobileFaceNet-MTCNN-FaceAntiSpoofing#1]
@syaringan357  Do you have this project in swift? Or supported for XCode 11.2.1? If you can provide MTCNN, Box, Tools, ios_image_load files in swift that would be great.

**Comment by zubingala** [comment]
@syaringan357 I'm facing difficulties in converting these files in swift. If you can help me.

**Comment by syaringan357** [comment]
Sorry, you have to support it yourself if you need it.

**Comment by hustle-lin** [comment]
Domain=org.tensorflow.lite.interpreter Code=1 "Input tensor at index (0) expects data size (27648), but got (0)." UserInfo={NSLocalizedDescription=Input tensor at index (0) expects data size (27648), but got (0).}    人脸检测的时候包错，请问如何解决

**Comment by syaringan357** [comment]
@hustle-lin interpreter.run() 方法第一个参数没有值，你需要把你的图片先放入一个数组，然后在调用这个方法时传入。
